# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c307ad556bb499314edfd281ab20290"
name = "shop-chat-agent"
application_url = "https://shop-chat-agent.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://shop-chat-agent.com/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
